config/routes.rb
Rails.application.routes.draw do

  root to: 'user/products#index'

  # TODO: adminsはnamespace: admin配下に持っていきたい。今はページがなくてやりづらいのであとで変更する。

  devise_for :admins, module: :admins_devises, controllers: {
    sessions:      'admins_devise/sessions',
    passwords:     'admins_devise/passwords'
  }

  devise_for :users, controllers: {
    confirmations: 'users_devise/confirmations',
    sessions:      'users_devise/sessions',
    passwords:     'users_devise/passwords',
    registrations: 'users_devise/registrations'
  }

  namespace :admin do
    root 'home#show'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products do
      collection do
        put 'update_sort_nos'
      end
    end
  end

  scope module: :user do
    get '/', to: 'products#index', as: :user_root
    resources :products, only: [:index] do
      resource :cart_product, only: [:new, :create, :destroy] do
        put :update_num
      end
    end
    resource :cart, only: [:edit, :show] do
      put 'fix_products'
      get 'edit_shipping_address'
      put 'fix_shipping_address'
      put 'purchase'
      get 'show_complete'
    end
    resources :purchase_histories, only: [:index, :show]
  end


end

app/models/cart.rb
class Cart < Purchase
  include ActiveSupport::NumberHelper

  enum state: {initial: 0, products_fixed: 2, shipping_address_fixed: 4, purchased: 10}

  validates :products_num, numericality: {only_integer: true, greater_than: 0, less_than: 10_000}, unless: -> {initial?}

  after_create do |purchase|
    purchase.create_shipping_address
  end
  before_validation :validate_state_transition
  before_update :calc_all,                              if: :initial?
  # 価格などの外部リソースの変化はlock_versionでチェックできないので購入確定時にチェックする。
  # しかし、確定するまでの間にもユーザに通知したい seel: #check_external_changes
  before_update :check_external_changes_without_update, if: :purchased?
  after_update :copy_to_purchase_history,               if: :purchased?
  after_update :copy_to_user_shipping_address,          if: :purchased?
  after_update :clear_all,                              if: :purchased?

  def add_product product, num
    # 追加時はショッピングカートのlock_versionが何であっても別に良い
    with_optimistic_retry(true) do
      catch(:loop_end) do
        self.purchase_products.each do |cart_product|
          if cart_product.product == product
            cart_product.name = product.name
            cart_product.price = product.price
            cart_product.num += num
            cart_product.total = cart_product.price * cart_product.num
            throw :loop_end
          end
        end
        cart_product = self.purchase_products.build({product: product, num: num})
        cart_product.name = product.name
        cart_product.price = product.price
        cart_product.total = cart_product.price * cart_product.num
      end
      self.state = Cart.states[:initial]
      self.save
    end
  end

  def update_product cart_lock_version, product, num
    self.reload
    self.purchase_products.each do |cart_product|
      if cart_product.product == product
        cart_product.num = num
        cart_product.total = cart_product.price * cart_product.num
        break
      end
    end
    self.lock_version = cart_lock_version.to_i
    self.state = Cart.states[:initial]
    self.save
  end

  def remove_product cart_lock_version, product
    self.reload
    self.purchase_products.each do |cart_product|
      cart_product.mark_for_destruction if cart_product.product == product
    end
    self.lock_version = cart_lock_version.to_i
    self.state = Cart.states[:initial]
    self.save
  end

  def fix_products lock_version
    self.reload
    self.lock_version = lock_version
    self.update(state: Cart.states[:products_fixed])
  end

  def fix_shipping_address ref_shipping_address: false, save_shipping_address:, delivery_scheduled_date:, delivery_scheduled_time:, lock_version:, shipping_address_attributes:
    self.reload
    cart_attributes = {
      ref_shipping_address:    ref_shipping_address,
      save_shipping_address:   save_shipping_address,
      delivery_scheduled_date: delivery_scheduled_date,
      delivery_scheduled_time: delivery_scheduled_time,
      lock_version:            lock_version,
      shipping_address_attributes: shipping_address_attributes
    }
    self.attributes = cart_attributes

    if self.ref_shipping_address?
      self.shipping_address.copy_from(self.user.shipping_address)
    end
    self.shipping_address.should_be_fixed = true
    self.state = Cart.states[:shipping_address_fixed]
    self.save
  end

  def purchase lock_version
    self.reload
    self.lock_version = lock_version
    self.state = Cart.states[:purchased]
    self.save
  end

  def check_external_changes with_update:
    messages = []

    if self.consumption_tax_rate.present? && self.consumption_tax_rate != ConsumptionTaxRate.current.rate
      messages << "消費税率が#{self.consumption_tax_rate}から#{ConsumptionTaxRate.current.rate}に変更になっているためショッピングカートをご確認ください。"
      self.consumption_tax_rate = ConsumptionTaxRate.current.rate if with_update
    end

    self.purchase_products.each do |purchase_product|
      if purchase_product.product.blank? || purchase_product.product.hidden?
        messages << "商品「#{purchase_product.name}」が販売中止になっているためショッピングカートをご確認ください。"
        purchase_product.mark_for_destruction if with_update
      else
        if purchase_product.name != purchase_product.product.name
          messages << "商品「#{purchase_product.product.name}」の名前が「#{purchase_product.name}」から「#{purchase_product.product.name}」に変更になっているためショッピングカートをご確認ください。"
          purchase_product.name = purchase_product.product.name if with_update
        end
        if purchase_product.price != purchase_product.product.price
          messages << "商品「#{purchase_product.product.name}」の価格が「#{number_to_currency(purchase_product.price)}」から「#{number_to_currency(purchase_product.product.price)}」に変更になっているためショッピングカートをご確認ください。"
          purchase_product.price = purchase_product.product.price if with_update
        end
      end
    end

    if self.shipping_address_fixed? || self.purchased?
      delivery_schedule = DeliverySchedule.new
      if self.delivery_scheduled_date.present?
        deliverable_dates = delivery_schedule.deliverable_dates
        if deliverable_dates.exclude?(self.delivery_scheduled_date)
          messages << "選択された配送日「#{self.delivery_scheduled_date}」が選択可能な配送期間（#{deliverable_dates.first}-#{deliverable_dates.last}）から外れてしまったため再度選択してください。"
          self.delivery_scheduled_date = nil if with_update
        end
      end
      if self.delivery_scheduled_time_start.present? && self.delivery_scheduled_time_end.present?
        deliverable_times = delivery_schedule.deliverable_times
        delivery_scheduled_time = DeliverySchedule.concat_times(self.delivery_scheduled_time_start, self.delivery_scheduled_time_end)
        if deliverable_times.exclude?(self.delivery_scheduled_time)
          messages << "選択された配送時間「#{delivery_scheduled_time}」が選択不可になってしまったため再度選択してください。"
          self.delivery_scheduled_time = nil if with_update
        end
      end
    end

    if messages.present?
      self.initial! if with_update
      raise ShouldRestartCartError.new(messages.join("\n"))
    end
  end

  def check_external_changes_without_update
    check_external_changes(with_update: false)
  end


  private

  def validate_state_transition
    if self.state_changed?
      if self.shipping_address_fixed? && self.state_was == 'initial'
        raise ShouldRestartCartError.new('ショッピングカート内の商品を確認してから送付先情報を保存してください。')
      elsif self.purchased? && ['initial', 'products_fixed'].include?(self.state_was)
        raise ShouldRestartCartError.new('送付先情報を保存してから確定してください。')
      end
    end
  end

  def calc_all
    logger.debug{"ショッピングカートを再計算します。(id: #{self.id})"}
    self.products_num, self.subtotal = calc_products_and_sum
    self.shipping_cost = calc_shipping_cost
    self.cod_fee = calc_cod_fee
    self.consumption_tax_rate, self.consumption_tax = calc_consumption_tax
    self.total = calc_total
  end

  def calc_products_and_sum
    num_and_subtotal = [0, 0]
    self.purchase_products.each do |cart_product|
      unless cart_product.marked_for_destruction?
        cart_product.total = cart_product.price * cart_product.num
        num_and_subtotal[0] += cart_product.num
        num_and_subtotal[1] += cart_product.total
      end
    end
    num_and_subtotal
  end

  def calc_shipping_cost
    ShippingCost.calc_current(self.products_num)
  end

  def calc_cod_fee
    if self.products_num > 0
      CodFee.calc_current(self.subtotal)
    else
      0
    end
  end

  def calc_consumption_tax
    current_tax = ConsumptionTaxRate.current
    [current_tax.rate, current_tax.calc(self.subtotal.to_i + self.shipping_cost.to_i + self.cod_fee.to_i)]
  end

  def calc_total
    self.subtotal + self.shipping_cost + self.cod_fee + self.consumption_tax
  end

  def copy_to_purchase_history
    # cart -> purchase_history
    attrs = self.dup.attributes
    attrs.delete("type")
    attrs.delete("lock_version")
    purchase_history = PurchaseHistory.new(attrs)
    purchase_history.purchased_at = Time.now
    purchase_history.state = PurchaseHistory.states[:purchased]

    # cart.purchase_products -> purchase_history.purchase_products
    self.purchase_products.each do |purchase_product|
      purchase_history.purchase_products << purchase_product.dup
    end

    # cart.shipping_address -> purchase_history.shipping_address
    purchase_history.shipping_address = self.shipping_address.dup

    purchase_history.save!
  end

  def copy_to_user_shipping_address
    if self.save_shipping_address?
      logger.debug{"送付先情報をユーザの送付先情報にコピー"}
      self.user.shipping_address.copy_from(self.shipping_address)
      self.user.shipping_address.save!
    end
  end

  def clear_all
    self.purchase_products.destroy_all
    self.shipping_address.clear
    clear
    self.save!
  end

  def clear
    attrs = Cart.new.attributes
    attrs[:state] = Cart.states[:initial]
    attrs.delete('id')
    attrs.delete('user_id')
    attrs.delete('lock_version')
    attrs.delete('created_at')
    attrs.delete('updated_at')
    self.attributes = attrs
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_one :shipping_address, as: :shippable, dependent: :destroy
  accepts_nested_attributes_for :shipping_address
  has_one :cart, dependent: :destroy
  has_many :purchase_histories, dependent: :nullify
  has_many :purchases

  validates :email, length: { maximum: 255 }

  after_create do |user|
    user.create_shipping_address
    user.create_cart(state: Cart.states[:initial])
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to [:admin, @user], notice: I18n.t('messages.updated')
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: I18n.t('messages.destroyed')
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(shipping_address_attributes: [:id, :name, :postal_code, :prefecture, :city, :address, :building])
    end
end

app/controllers/user/application_controller.rb
class User::ApplicationController < ApplicationController
  before_action :store_user_location!, if: :storable_location?

  private

  # ログイン後、元々リクエストのあったベージに移動するための設定
  # see: https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update
  def store_user_location!
    store_location_for(:user, request.fullpath)
  end
end

app/controllers/user/cart_products_controller.rb
class User::CartProductsController < User::ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :set_product
  before_action :set_cart, except: [:new]
  before_action :set_cart_product, only: [:create, :update_num]

  rescue_from StandardError do |exception|
    respond_to do |format|
      format.js do
        logger_error exception
        flash[:alert] = "処理を続行できませんでした。しばらくしてから再度実施してください。"
        js_redirect_to edit_cart_path
      end
      format.html { raise exception}
    end
  end

  rescue_from ActiveRecord::StaleObjectError do |exception|
    respond_to do |format|
      format.js do
        flash[:alert] = I18n.t('activerecord.errors.messages.stale_object', record: Cart.model_name.human)
        js_redirect_to edit_cart_path
      end
      format.html { raise exception}
    end
  end

  def new
    @cart_product = @product.purchase_products.build
  end

  def create
    if @cart_product.valid_attribute?(:num) && @cart.add_product(@product, @cart_product.num)
      redirect_to edit_cart_path, notice: "#{Cart.model_name.human}に保存しました"
    else
      render :new
    end
  end

  # for ajax
  def update_num
    if @cart_product.invalid_attribute?(:num)
      render :update_num
    elsif @cart.update_product(params[:lock_version], @product, @cart_product.num)
      @cart_product = @cart.purchase_products.find_by(product:  @product)
      flash.now[:notice] = I18n.t('messages.updated')
      render :update_num
    else
      flash.now[:alert] = @cart_product.joined_messages
      render partial: 'shared/messages', formats: :js
    end
  end

  # for ajax
  def destroy
    if @cart.remove_product(params[:lock_version], @product)
      flash.now[:notice] = I18n.t('messages.destroyed')
    else
      # ありえないと思うけど、念のため
      flash.now[:alert] = @cart_product.joined_messages
      render partial: 'shared/messages', formats: :js
    end
  end

  private
    def set_product
      @product = Product.find(params[:product_id])
    end

    def set_cart
      @cart = current_user.cart
    end

    def set_cart_product
      @cart_product = @product.purchase_products.build(cart_product_params)
      @cart_product.purchase = @cart
    end

    def cart_product_params
      params.require(:purchase_product).permit(:num)
    end
end

app/controllers/user/carts_controller.rb
class User::CartsController < User::ApplicationController
  before_action :authenticate_user!
  before_action :set_cart
  before_action :set_delivery_schedule, only: [:edit_shipping_address, :fix_shipping_address]
  before_action :check_external_changes_with_update, only: [:edit, :edit_shipping_address, :show]

  rescue_from ActiveRecord::StaleObjectError do |exception|
    redirect_to edit_cart_path, alert: I18n.t('activerecord.errors.messages.stale_object', record: Cart.model_name.human)
  end

  def show
  end

  def show_complete
  end

  def edit
    unless @cart.purchase_products.any?
      flash.now.notice = "#{Cart.model_name.human}は空です"
    end
  end

  def edit_shipping_address
    if @cart.ref_shipping_address.nil? && current_user.shipping_address.available?
      @cart.ref_shipping_address = true
    end
    if @cart.ref_shipping_address?
      # 保存した後、再度この画面に戻ってくると表示されてしまうので消しておく
      @cart.shipping_address.clear
    end
  end

  def fix_products
    if @cart.fix_products(params.require(:cart)[:lock_version])
      redirect_to edit_shipping_address_cart_path
    else
      # 画面に表示できるようなvalidationエラーは発生していないはず
      logger.error @cart.joined_messages
      redirect_to edit_cart_path, alert: "処理を続行できませんでした。しばらくしてから再度実施してください。"
    end
  end

  def fix_shipping_address
    args = params.require(:cart).permit(
      :ref_shipping_address, :save_shipping_address, :delivery_scheduled_date, :delivery_scheduled_time, :lock_version,
      shipping_address_attributes: [:id, :name, :postal_code, :prefecture, :city, :address, :building]).to_unsafe_hash.symbolize_keys
    if @cart.fix_shipping_address(**args)
      redirect_to cart_path
    else
      render :edit_shipping_address
    end
  end

  def purchase
    if @cart.purchase(params.require(:cart)[:lock_version])
      redirect_to show_complete_cart_path
    else
      # 画面に表示できるようなvalidationエラーは発生していないはず
      logger.error @cart.joined_messages
      redirect_to edit_shipping_address_cart_path, alert: "処理を続行できませんでした。しばらくしてから再度実施してください。"
    end
  rescue ShouldRestartCartError => e
    redirect_to edit_cart_path
  end

  private

  def set_cart
    @cart = current_user.cart
  end

  def set_delivery_schedule
    @delivery_schedule = DeliverySchedule.new
  end

  def check_external_changes_with_update
    @cart.check_external_changes(with_update: true)
  rescue ShouldRestartCartError => e
    begin
      logger.info "ShouldRestartCartError occured: #{e.message}"
      flash.now[:alert] = e.message
    rescue StandardError => e
      logger.fatal(e.message)
      logger.fatal(e.backtrace)
    end
  end
end

app/controllers/user/products_controller.rb
class User::ProductsController < User::ApplicationController
  before_action :set_product, only: [:show]

  def index
    @products = Product.published.order(:sort_no).page(params[:page]).per(20).all
  end

  def show
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/user/purchase_histories_controller.rb
class User::PurchaseHistoriesController < User::ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show]

  def index
    @purchase_histories = PurchaseHistory.includes(:purchase_products).order("purchased_at desc").page(params[:page]).all
  end

  def show
  end

  private
    def set_product
      @purchase_history = PurchaseHistory.find(params[:id])
    end
end

app/views/user/carts/_num.html.haml
%div{style: ('display: none' if cart_product.errors[:num].present?)}
  = cart_product.num
  = link_to "変更", "javascript:void(0)", {id: dom_id(cart_product.product, :num_change), remote: false}

= simple_form_for(cart_product, url: update_num_product_cart_product_path(cart_product.product),
      method: :put, remote: true,
      html: {class: 'form-inline', style: ('display: none' unless cart_product.errors[:num].present?)}) do |f|
  = hidden_field_tag "lock_version", cart_product.purchase.lock_version, data: {lock_version: ''}, id: nil
  = f.input :num, input_html: {class: 'form-control input-sm form-inline', style: 'width: 60px', id: nil, display: 'inline'}, label: false
  = f.submit "更新"

app/views/user/carts/_total.html.haml
%tfoot{id: 'total'}
  %tr
    %td.text-right{colspan: 4}= Cart.human_attribute_name(:subtotal)
    %td.text-right= number_to_currency cart.subtotal
  %tr
    %td.text-right{colspan: 4}= Cart.human_attribute_name(:shipping_cost)
    %td.text-right= number_to_currency cart.shipping_cost
  %tr
    %td.text-right{colspan: 4}= Cart.human_attribute_name(:cod_fee)
    %td.text-right= number_to_currency cart.cod_fee
  %tr
    %td.text-right{colspan: 4}= "#{Cart.human_attribute_name(:consumption_tax)}(#{cart.consumption_tax_rate}%)"
    %td.text-right= number_to_currency cart.consumption_tax
  %tr
    %td.text-right{colspan: 4}= Cart.human_attribute_name(:total)
    %td.text-right= number_to_currency cart.total

app/views/user/carts/edit.html.haml
- if @cart.purchase_products.present?
  %div#cart
    %h1= "#{Cart.model_name.human}の編集"

    %table.table-striped.table-hover
      %thead
        %tr
          %th{style: "width: 10%"}= PurchaseProduct.human_attribute_name(:product)
          %th{style: "width: 35%"}
          %th.text-right{style: "width: 15%"}= PurchaseProduct.human_attribute_name(:price)
          %th.text-right{style: "width: 15%"}= PurchaseProduct.human_attribute_name(:num)
          %th.text-right{style: "width: 15%"}= PurchaseProduct.human_attribute_name(:total)
          %th{style: "width: 10%"}
      %tbody
        - @cart.purchase_products.each do |purchase_product|
          - product = purchase_product.product
          %tr{id: dom_id(product)}
            %td= image_tag product.product_image_url(:thumb), class: 'media-object'
            %td= purchase_product.name
            %td.text-right= number_to_currency purchase_product.price
            %td.text-right{id: dom_id(product, :num)}
              = render 'num', cart_product: purchase_product
            %td.text-right{id: dom_id(product, :total)}
              = number_to_currency purchase_product.total
            %td.text-center
              = link_to "削除", "javascript:void(0)", method: :delete
              = simple_form_for(purchase_product, url: product_cart_product_path(product), method: :delete, remote: true, html: {style: 'display: none'}) do |f|
                = hidden_field_tag "lock_version", @cart.lock_version, data: {lock_version: ''}, id: nil
                = f.submit "削除"

      = render 'total', cart: @cart

    .form-actions
      = simple_form_for(@cart, url: fix_products_cart_path, method: :put) do |f|
        = f.input :lock_version, as: :hidden, input_html: {data: {lock_version: ''}}
        = f.button :submit, "#{ShippingAddress.model_name.human}の編集画面に進む", class: 'btn-primary', name: 'fix_products'

:coffee
  $("a[data-method=delete]").click ->
    Rails.fire($(this).siblings("form").get(0), 'submit')
  $(document).on "click", "td a[id*=num_change]", ->
    $(this).closest("td").children("div").hide()
    $(this).closest("td").children("form").show()

app/views/user/carts/edit_shipping_address.html.haml
%h1= "#{ShippingAddress.model_name.human}の編集"

= simple_form_for(@cart, url: fix_shipping_address_cart_path, method: :put) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :lock_version, as: :hidden
  - if current_user.shipping_address.available?
    .radio
      %label
        = f.radio_button 'ref_shipping_address', true
        %div= "以前保存した#{ShippingAddress.model_name.human}を使用"
        = render 'shared/address', shipping_address: current_user.shipping_address

    .radio
      %label
        = f.radio_button 'ref_shipping_address', false
        = "別の#{ShippingAddress.model_name.human}を使用（以下のフォームに入力してください）"

  = f.fields_for :shipping_address do |f_inner|
    .form-inputs= f_inner.input :name
    .form-inputs= f_inner.input :postal_code
    .form-inputs= f_inner.input :prefecture
    .form-inputs= f_inner.input :city
    .form-inputs= f_inner.input :address
    .form-inputs= f_inner.input :building
  .form-inputs= f.input :save_shipping_address

  %h2= "#{DeliverySchedule.model_name.human}"

  .form-inputs= f.input :delivery_scheduled_date, collection: @delivery_schedule.deliverable_dates
  .form-inputs= f.input :delivery_scheduled_time, collection: @delivery_schedule.deliverable_times

  .form-actions
    = link_to "戻る", edit_cart_path, class: 'btn btn-primary'
    = f.button :submit, "確認画面に進む", class: 'btn-primary', name: 'fix_shipping_address'

app/views/user/carts/show.html.haml
%h1= "#{Cart.model_name.human}の確認"

%table.table-striped.table-hover
  %thead
    %tr
      %th{style: "width: 10%"}= PurchaseProduct.human_attribute_name(:product)
      %th{style: "width: 35%"}
      %th.text-right{style: "width: 15%"}= PurchaseProduct.human_attribute_name(:price)
      %th.text-right{style: "width: 15%"}= PurchaseProduct.human_attribute_name(:num)
      %th.text-right{style: "width: 15%"}= PurchaseProduct.human_attribute_name(:total)
      %th{style: "width: 10%"}

  %tbody
    - @cart.purchase_products.each do |purchase_product|
      %tr{id: dom_id(purchase_product.product)}
        %td= image_tag purchase_product.product.product_image_url(:thumb), class: 'media-object'
        %td= purchase_product.name
        %td.text-right= number_to_currency purchase_product.price
        %td.text-right= number_with_delimiter purchase_product.num
        %td.text-right= number_to_currency purchase_product.total
  = render 'total', cart: @cart

%h2= "#{ShippingAddress.model_name.human}の確認"
= render 'shared/address', shipping_address: @cart.shipping_address

%h2= "#{DeliverySchedule.model_name.human}の確認"
= render 'shared/delivery_schedule', cart: @cart

.form-actions
  = simple_form_for(@cart, url: purchase_cart_path, method: :put) do |f|
    = f.input :lock_version, as: :hidden
    = link_to "戻る", edit_shipping_address_cart_path, class: 'btn btn-primary'
    = f.button :submit, "確定", class: 'btn-primary', name: 'purchase'

app/views/user/carts/show_complete.html.haml
%h1= "ご購入ありがとうございました"