config/routes.rb
Rails.application.routes.draw do

  root to: 'user/products#index'

  # TODO: adminsはnamespace: admin配下に持っていきたい。今はページがなくてやりづらいのであとで変更する。

  devise_for :admins, module: :admins_devises, controllers: {
    sessions:      'admins_devise/sessions',
    passwords:     'admins_devise/passwords'
  }

  devise_for :users, controllers: {
    confirmations: 'users_devise/confirmations',
    sessions:      'users_devise/sessions',
    passwords:     'users_devise/passwords',
    registrations: 'users_devise/registrations'
  }

  namespace :admin do
    root 'home#show'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products do
      collection do
        put 'update_sort_nos'
      end
    end
  end

  scope module: :user do
    get '/', to: 'products#index', as: :user_root
    resources :products, only: [:index] do
      resource :cart_product, only: [:new, :create, :destroy] do
        put :update_num
      end
    end
    resource :cart, only: [:edit, :show] do
      put 'fix_products'
      get 'edit_shipping_address'
      put 'fix_shipping_address'
      put 'purchase'
      get 'show_complete'
    end
    resources :purchase_histories, only: [:index, :show]
  end


end

app/views/layouts/admin/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title さくらマーケット管理
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag('application_admin', {media: 'all', 'data-turbolinks-track': 'reload'})
    = javascript_include_tag('application_admin', {'data-turbolinks-track': 'reload'})
  %body
    - if admin_signed_in?
      %nav.navbar.navbar-default.navbar-fixed-top
        .container-fluid
          .navbar-header
            %a.navbar-brand{href: admin_root_path} さくらマーケット管理
          .collapse.navbar-collapse
            %ul.nav.navbar-nav
              = nav_item(User.model_name.human, admin_users_path, 'users')
              = nav_item(Product.model_name.human, admin_products_path, 'products')
            %ul.nav.navbar-nav.navbar-right
              %li= link_to "ログアウト", destroy_admin_session_path, class: "navbar-link", method: 'delete'
    %main.container{role: "main", class: ("devise_main" if devise_controller?)}
      = render "shared/messages", alert: :info, messages: notice
      = render "shared/messages", alert: :danger, messages: alert
      = yield