config/routes.rb
Rails.application.routes.draw do

  root to: 'user/products#index'

  # TODO: adminsはnamespace: admin配下に持っていきたい。今はページがなくてやりづらいのであとで変更する。

  devise_for :admins, module: :admins_devises, controllers: {
    sessions:      'admins_devise/sessions',
    passwords:     'admins_devise/passwords'
  }

  devise_for :users, controllers: {
    confirmations: 'users_devise/confirmations',
    sessions:      'users_devise/sessions',
    passwords:     'users_devise/passwords',
    registrations: 'users_devise/registrations'
  }

  namespace :admin do
    root 'home#show'
    resources :users, only: [:index, :show, :edit, :update, :destroy]
    resources :products do
      collection do
        put 'update_sort_nos'
      end
    end
  end

  scope module: :user do
    get '/', to: 'products#index', as: :user_root
    resources :products, only: [:index] do
      resource :cart_product, only: [:new, :create, :destroy] do
        put :update_num
      end
    end
    resource :cart, only: [:edit, :show] do
      put 'fix_products'
      get 'edit_shipping_address'
      put 'fix_shipping_address'
      put 'purchase'
      get 'show_complete'
    end
    resources :purchase_histories, only: [:index, :show]
  end


end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :product_image, ProductImageUploader

  has_many :purchase_products, dependent: :restrict_with_exception
  has_many :purchases, through: :purchase_products

  validates :name, presence: true,
                   uniqueness: true
  validates :price, presence: true, if: -> {!hidden}
  validates :price, numericality: {only_integer: true, less_than: 10_000_000}, if: -> {price.present?}
  validates :description, length: { maximum: 500 }
  validates :sort_no, presence: true, if: -> {!hidden}
  validates :sort_no, numericality: {only_integer: true, less_than: 1_000_000}, if: -> {sort_no.present?}
  validates :product_image, presence: true, if: -> {!hidden}
  validates :remove_product_image, exclusion: { in: ["1"], message: "は公開中に実施できません" }, if: -> {!hidden}

  scope :published, -> {where(products: {hidden: false})}

  def self.update_sort_nos ids
    return if ids.blank?

    id_and_sort_no_hash = ids.each_with_index.map{|id, index| [id.to_i, index]}.to_h
    Product.transaction do
      Product.all.each do |product|
        product.update_attribute(:sort_no, id_and_sort_no_hash[product.id].to_i)
      end
    end
  end

  def hidden_name
    if hidden
      "非表示"
    else
      "表示"
    end
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::DeleteRestrictionError do |exception|
    redirect_to admin_products_url, notice: "この商品がショッピングカートに入っている、または購入されているため削除できません。"
    # タイミングの問題でRailsが誤判断しても外部キー制約があるので削除できない。ただし、500エラーになるのでユーザーフレンドリーではない。
    # exception.sql_state
    # => "23000"
    # exception.error
    # => "Cannot delete or update a parent row: a foreign key constraint fails (`sg_ec_development`.`purchase_products`, CONSTRAINT `fk_rails_57ad37ee9d` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`))"
    # exception.errno
    # => 1451
    # exception.error_number
    # => 1451
  end

  def index
    @products = Product.order(:sort_no).all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, @product], notice: I18n.t('messages.created')
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to [:admin, @product], notice: I18n.t('messages.updated')
    else
      render :edit
    end
  end

  def update_sort_nos
    Product.update_sort_nos(params[:ids].try(:split, ","))

    redirect_to admin_products_path, notice: "#{Product.human_attribute_name(:sort_no)}を変更しました"
  end

  def destroy
    @product.destroy
    redirect_to admin_products_url, notice: I18n.t('messages.destroyed')
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :description, :hidden, :sort_no, :product_image, :remove_product_image)
    end
end

app/controllers/user/products_controller.rb
class User::ProductsController < User::ApplicationController
  before_action :set_product, only: [:show]

  def index
    @products = Product.published.order(:sort_no).page(params[:page]).per(20).all
  end

  def show
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
end

app/views/admin/products/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([:admin, @product]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :price
    = f.input :description
    = f.input :hidden
    = f.input :sort_no
    = f.input :product_image, as: :file
    = image_tag(@product.product_image_url) if @product.product_image?
    = f.input :remove_product_image, as: :boolean
  .form-actions
    = f.button :submit, class: 'btn-primary'

app/views/admin/products/edit.html.haml
%h1= "#{Product.model_name.human}の編集"

= render 'form'

= link_to I18n.t('links.show'), [:admin, @product]
\|
= link_to I18n.t('links.back'), admin_products_path

app/views/admin/products/index.html.haml
%h1= "#{Product.model_name.human}の一覧"

%table.table-striped.table-bordered.table-hover{id: 'products'}
  %thead
    %tr
      %th= Product.human_attribute_name(:name)
      %th= Product.human_attribute_name(:price)
      %th= Product.human_attribute_name(:description)
      %th= Product.human_attribute_name(:hidden)
      %th= Product.human_attribute_name(:sort_no)
      %th
      %th
      %th

  %tbody
    - @products.each do |product|
      %tr{data: {product: product.id}}
        %td= product.name
        %td.text-right= number_with_delimiter(product.price)
        %td= product.description
        %td= product.hidden_name
        %td.text-right
          = number_with_delimiter(product.sort_no)
        %td= link_to I18n.t('links.show'), [:admin, product]
        %td= link_to I18n.t('links.edit'), edit_admin_product_path(product)
        %td= link_to I18n.t('links.destroy'), [:admin, product], method: :delete, data: { confirm: I18n.t('messages.confirm') }

%br

= link_to I18n.t('links.new'), new_admin_product_path
- if @products.size > 1
  |
  = link_to "#{Product.human_attribute_name(:sort_no)}を変更する", 'javascript:void(0)', id: 'edit_sort_nos'
  = form_tag(update_sort_nos_admin_products_path, id: 'update_sort_nos', style: 'display: none', method: 'put') do
    = link_to "#{Product.human_attribute_name(:sort_no)}を変更しない", admin_products_path
    = hidden_field nil, :ids, id: 'ids'
    = submit_tag "#{Product.human_attribute_name(:sort_no)}を確定する", class: 'btn btn-primary'
  :coffee
    $(document).on 'turbolinks:load', ->
      $('#edit_sort_nos').on 'click', ->
        $('#products > tbody').sortable()
        $('#products > tbody > tr').css('cursor', 'move')
        $('#edit_sort_nos').hide()
        $('#update_sort_nos').css(display: 'inline')

      $('#update_sort_nos').on 'submit', ->
        ids = $('#products > tbody > tr').map ->
          $(this).data('product')
        $('#ids').val(ids.get().join(','))

app/views/admin/products/new.html.haml
%h1= "#{Product.model_name.human}の新規作成"

= render 'form'

= link_to I18n.t('links.back'), admin_products_path

app/views/admin/products/show.html.haml
%p
  %b= "#{Product.human_attribute_name :name}:"
  = @product.name
%p
  %b= "#{Product.human_attribute_name :price}:"
  = @product.price
%p
  %b= "#{Product.human_attribute_name :description}:"
  = @product.description
%p
  %b= "#{Product.human_attribute_name :hidden}:"
  = @product.hidden_name
%p
  %b= "#{Product.human_attribute_name :sort_no}:"
  = @product.sort_no
%p
  %b= "#{Product.human_attribute_name :product_image}:"
  %div= image_tag(@product.product_image_url(:thumb)) if @product.product_image?

= link_to I18n.t('links.edit'), edit_admin_product_path(@product)
\|
= link_to I18n.t('links.back'), admin_products_path